// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpxNOTdgFfQUhcKPSvmRB5S5zUM4b_X-I',
    appId: '1:114709490168:web:fc0e065a6a0d714449ce0d',
    messagingSenderId: '114709490168',
    projectId: 'heal-point',
    authDomain: 'heal-point.firebaseapp.com',
    storageBucket: 'heal-point.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlBfEc4mn42VhDmgDoQc-tDpjcUUtuzLk',
    appId: '1:114709490168:android:bc7cb8a889fcc3c349ce0d',
    messagingSenderId: '114709490168',
    projectId: 'heal-point',
    storageBucket: 'heal-point.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqnLHN2GCQeX2VfKZo6_hhFEmELFiQX9w',
    appId: '1:114709490168:ios:939d675dda43178449ce0d',
    messagingSenderId: '114709490168',
    projectId: 'heal-point',
    storageBucket: 'heal-point.appspot.com',
    iosClientId: '114709490168-5ujkdjv8i2r13s34147j4a6cka5i4ng9.apps.googleusercontent.com',
    iosBundleId: 'com.chen237.app',
  );
}
